### ISSUE TITLE
viem-op extensions compatibility with cel2

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/viem#15]
### l1 fees (absent on cel2)
If we deploy a contract with the [GasPriceOracle Interface ](https://github.com/ethereum-optimism/optimism/blob/233ede59d16cb01bdd8e7ff662a153a4c3178bdd/packages/contracts/contracts/L2/predeploys/OVM_GasPriceOracle.sol)that returns 0 then any function from viem that calls L1fees will still work for cel2.

[#306](https://github.com/celo-org/celo-blockchain-planning/issues/306)

## fault proof / game related

- [ ] unclear so far how functions that related to [DisputeGameFactoryProxy contract](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/extra/addresses/addresses.json) will be affected

**Comment by aaronmgdr** [comment]
S but there is uncertainty so L

**Comment by aaronmgdr** [comment]
knowing the time on this requires going thru each function seeing what it does and then conferring wit blockchain team about differences in cel2 and op main

**Comment by aaronmgdr** [comment]
Note until we have a clear spec for what happens with DA layer its not clear what we can do for the alternate to the gasPrice /L1 fees call that will break on celo.

**Comment by aaronmgdr** [comment]
note i took out the parts of the ticket we can actually do an put them in [#309](https://github.com/celo-org/celo-blockchain-planning/issues/309)

**Comment by lvpeschke** [comment]
Blocked on https://github.com/celo-org/celo-blockchain-planning/issues/163

**Comment by aaronmgdr** [comment]
todo test out the existing viem op stack extentions and see how using them without modification is like.

**Comment by aaronmgdr** [comment]
replaced with https://github.com/celo-org/celo-blockchain-planning/issues/423
