### ISSUE TITLE
Remove `feeCurrency`, `gatewayFee`, and `gatewayFeeRecipient` properties from transaction receipts

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/viem#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.16.0

### Description

I build the following CIP-42 transaction. 

Note that I specify cUSD as the fee currency:

```ts
const transactionHash = await client.sendTransaction({
        account, // Sender
        to: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8", // Recipient (illustrative address)
        value: parseEther("0.01"), // 0.01 CELO
        feeCurrency: "0x874069Fa1Eb16D44d622F2e0Ca25eeA172369bC1", // cUSD fee currency
        maxFeePerGas: parseGwei("10"), // Special field for dynamic fee transaction type (EIP-1559)
        maxPriorityFeePerGas: parseGwei("10"), // Special field for dynamic fee transaction type (EIP-1559)
    });
```

Source: [0xarthurxyz/txtypes](https://github.com/0xarthurxyz/txtypes/blob/main/demo.ts)

When I parse (and format) the transaction receipt with:

```ts
const transactionReceipt = await publicClient.waitForTransactionReceipt({
        hash: await transactionHash,
});

printFormattedTransactionReceipt(transactionReceipt);
```
The `feeCurrency` field is `undefined`. 

```diff
Transaction details: {
  type: '0x7c',
  status: 'success',
  transactionHash: '0x9935c26499205b028a2518cfa5a32b7ebf68533deec414c8ded9f91ae5aa5dd8',
  from: '0x303c22e6ef01cba9d03259248863836cb91336d5',
  to: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
  feeCurrency: undefined
} 
```

This is expected, because the `feeCurrency`, `gatewayFee`, and `gatewayFeeRecipient` fields are never included in a transaction receipt. See [here](https://github.com/celo-org/celo-blockchain/blob/master/internal/ethapi/api.go#L2067) where the transaction receipt is defined in the Celo blockchain client. 

That means the 3 fields can be removed from the transaction receipt

```diff
transactionReceipt: /*#__PURE__*/ defineTransactionReceipt({
    format(
      args: CeloRpcTransactionReceiptOverrides,
    ): CeloTransactionReceiptOverrides {
      return {
-        feeCurrency: args.feeCurrency,
-        gatewayFee: args.gatewayFee ? hexToBigInt(args.gatewayFee) : null,
-        gatewayFeeRecipient: args.gatewayFeeRecipient,
      }
    },
  }),
```

See Slack discussion with the Blockchain team [here](https://celo-org.slack.com/archives/CNJ7KTHQU/p1698688855441649).

**Comment by arthurgousset** [comment]
Sprint planning: 
- This was added by the viem team at the time.

**Comment by arthurgousset** [comment]
Paired on this with @nicolasbrugneaux today: 
- https://github.com/wagmi-dev/viem/pull/1500

**Comment by 0xarthurxyz** [comment]
Closing this issue in favour of the PR: 
- https://github.com/wevm/viem/pull/1500

**Comment by arthurgousset** [comment]
Closing this because it's merged
